<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a0a757365722e70726f746f22300a0b5573657252657175657374120f0a076163636f756e7418012001280912100a0870617373776f726418022001280922330a0c55736572526573706f6e736512120a0a6163636f756e745f6964180120012805120f0a076163636f756e74180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

