<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>UserResponse</code>
 */
class UserResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 account_id = 1;</code>
     */
    protected $account_id = 0;
    /**
     * Generated from protobuf field <code>string account = 2;</code>
     */
    protected $account = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $account_id
     *     @type string $account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 account_id = 1;</code>
     * @return int
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>int32 account_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkInt32($var);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

}

